# .github/workflows/ci.yml
name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
